### ISSUE TITLE
future features...

### ISSUE THREAD

**Issue by satellaview-dev** [satellaview-dev/voxelshock#1]
# TODO:
- [ ] Add and test VR support / compatibility with Vivecraft mod.
- [ ] Complete custom soundtrack for the modpack.
- [ ] Finish writing the documentation / manual.
- [ ] Full controller testing
- [ ] Find a way to get shaders working WITHOUT optifine (iris has a 1.19.3 version,  but the rubidium[iris on forge port] devs just. refuse to port the thing. I don't even need it to be updated, I'd just like it to work.)

**Comment by satellaview-dev** [comment]
I doubt the shaders will ever work until i learn more java
Boring
